### ISSUE TITLE
Why not `push` after `publish`?

### ISSUE THREAD

**Issue by tomek-he-him** [kimmobrunfeldt/releasor#1]
Hi,

when rolling out a release I normally `push` only if the `publish` succeeds:

```
$ npm version patch && npm publish && git push --follow-tags
```

When `npm publish` fails, I don’t push my tag to the remote – which is a good thing. I noticed in the readme that you do it the other way round. Have you considered otherwise?

**Comment by kimmobrunfeldt** [comment]
This would be a good fix. Currently the recovering of a failure is pretty much delegated to the user.
