### ISSUE TITLE
Support .releasorrc files for global repo configuration

### ISSUE THREAD

**Issue by OtaK** [kimmobrunfeldt/releasor#2]
Hi,

I find it cumbersome to pass parameters such as --tag "v{{version}" each time, wouldn't it be better to actually have a `.releasorrc` JSON file at the root of the repo that defines standard configuration for Releasor?

Thanks,
Have a great day,
Mathieu Amiot

**Comment by kimmobrunfeldt** [comment]
That could be a good way to define the configuration yeah. I'm very open for a pull request if someone wants to implement this feature.

**Comment by OtaK** [comment]
@kimmobrunfeldt 
Done in #3 :-)

Also, check out #4 too, I guess it's an interesting change to lower package size.

**Comment by OtaK** [comment]
This should be closed then :)
